### PR TITLE
feat(DomainHierarchy): filter out apps and roles

### PR DESCRIPTION
**Pull request by Harasz**
Filter out apps and roles namespaces using DomainHierarchy::getSubdomainsUsingResolver() method

### CODE REVIEW

**Comment by jrhender** [comment]
I think this might fix the issue, but could you check the tests and add one (or more) to cover the scenario that was missing

**Comment by jrhender** [comment]
@Harasz This looks good, thanks for adding the test. Maybe just missing a test in the case that the param is `FIRSTLEVEL` instead of `ALL`.

**Comment by jrhender** [comment]
Once you move PR to "ready" from "draft", let me know and I will review again

**Comment by Harasz** [comment]
@jrhender PR is ready for review

**Review by jrhender — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
